name: Check and Update Suburb Data

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  update-suburb-data:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pandas beautifulsoup4 requests

    - name: Run script to check and update suburb data
      run: |
        python duplicates.py

    - name: Upload updated CSV
      uses: actions/upload-artifact@v3
      with:
        name: updated_health_data
        path: updated_health_data.csv
